### ISSUE TITLE
sysStat.Cputemp is empty

### ISSUE THREAD

**Issue by li-wilbur** [jakeslee/ikuai-exporter#2]
Ikuai 版本信息
![image](https://github.com/jakeslee/ikuai-exporter/assets/43690717/bc420077-d67c-4745-a4eb-264b9a5e8020)

容器报错信息
2023/09/29 18:07:23 exporter v0.0.9-0-g5f1de2 started at :9090
2023/09/29 18:07:27 sysStat.Cputemp is empty
2023/09/29 18:07:35 sysStat.Cputemp is empty
2023/09/29 18:07:43 sysStat.Cputemp is empty
2023/09/29 18:07:51 sysStat.Cputemp is empty
2023/09/29 18:07:59 sysStat.Cputemp is empty
2023/09/29 18:08:07 sysStat.Cputemp is empty
2023/09/29 18:08:15 sysStat.Cputemp is empty
2023/09/29 18:08:23 sysStat.Cputemp is empty
2023/09/29 18:08:31 sysStat.Cputemp is empty
2023/09/29 18:08:39 sysStat.Cputemp is empty
2023/09/29 18:08:47 sysStat.Cputemp is empty
2023/09/29 18:08:55 sysStat.Cputemp is empty
2023/09/29 18:09:03 sysStat.Cputemp is empty

**Comment by jakeslee** [comment]
请问是使用虚拟机搭建的 ikuai 吗？我这边如果用的是虚拟机搭建的确实是会有这个提示，爱快的接口不返回温度信息。

**Comment by justs0o** [comment]
我也是虚拟机，报错这个

**Comment by jakeslee** [comment]
> 我也是虚拟机，报错这个

如果是虚拟机的话忽略这个提示就好了。
