### ISSUE TITLE
频繁登录问题的建议

### ISSUE THREAD

**Issue by HolyGu** [jakeslee/ikuai-exporter#4]
目前的镜像是每隔2秒钟登录一次爱快去读取数据，这样会造成爱快的登录日志被脚本的登录请求覆盖到只能保留约3个小时，容易覆盖掉正常日志，可否考虑改为脚本登陆后保存cookie，后面通过cookie去调用接口，如cookie失效再去登录重新获取cookie
<img width="1695" alt="image" src="https://github.com/jakeslee/ikuai-exporter/assets/28488437/b96d3a79-4978-4a81-babb-52ba45ed9901">
<img width="1696" alt="image" src="https://github.com/jakeslee/ikuai-exporter/assets/28488437/a5a85796-6ae8-4652-ab79-7fb0bde3cad3">

**Comment by jakeslee** [comment]
对登录做了一下优化，极大减少了登录日志的产生。可以拉取最新版本镜像使用：
```
jakes/ikuai-exporter:v0.1.1-0-g6ac7f1
```
